spring:
  config:
    import:
      - 'properties-common.yml'
      - 'properties-common-test.yml'
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: ${datasource.driver-class-name}
