spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_management
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  batch:
    job:
      enabled: false # Disable automatic job execution on startup
    jdbc:
      initialize-schema: always

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.employee.common.model
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

logging:
  level:
    com.example.employee: DEBUG
    org.springframework.batch: INFO
